# Automatically generated file. Do not edit.

CONFIG_ACPI := y
CONFIG_VRAY := y
CONFIG_VNODE := y
CONFIG_NVNODE := y
CONFIG_XHCI := y
CONFIG_AHCI := n
CONFIG_PS2 := y
CONFIG_VFS := y
CONFIG_RAMFS := y
CONFIG_FAT32 := y
CONFIG_DEBUG_SERIAL := y
CONFIG_SMP := y
CONFIG_SMT_SCHED := y
CONFIG_CPU_FREQ := y
CONFIG_CPU_FREQ_INTEL := y
CONFIG_IOSCHED_MQ_DEADLINE := y
CONFIG_IOSCHED_KYBER := y
CONFIG_IOSCHED_BFQ := y
CONFIG_USB_HID := y
CONFIG_USB_KBD := y
