timeout: 5
serial: yes
wallpaper: boot():/boot/rhoudveine_raindrops.png

/Rhoudveine OS
    protocol: limine
    kernel_path: boot():/boot/rhoudveine
    module_path: boot():/System/Rhoudveine/Booter/init
    module_cmdline: /System/Rhoudveine/Booter/init
    module_path: boot():/System/Rhoudveine/rootfs.tar
    module_cmdline: rootfs.tar
