#!/usr/bin/env python3
"""
gen_usb_ids.py  —  Convert usb.ids into usb_ids_generated.h
Usage: python3 gen_usb_ids.py usb.ids > include/usb_ids_generated.h

Output is a sorted flat array of { vid, pid, vendor, product } structs
plus a bsearch-friendly lookup function.  The generated file is pure C99
with no dynamic allocation — safe to include directly in a freestanding kernel.

Devices with no printable name are skipped.
Interface lines (two tabs) are ignored.
"""

import sys
import re

def escape_c(s):
    """Escape a string for use as a C string literal."""
    return s.replace('\\', '\\\\').replace('"', '\\"')

def parse_usb_ids(path):
    vendors = []   # list of (vid_int, vendor_name, [(pid_int, product_name), ...])
    current_vendor = None

    with open(path, 'r', encoding='utf-8', errors='replace') as f:
        for line in f:
            # Strip trailing newline only (preserve leading tabs)
            line = line.rstrip('\n\r')

            # Skip blank lines and comments
            if not line or line.startswith('#'):
                continue

            # Interface line (two tabs) — ignore
            if line.startswith('\t\t'):
                continue

            # Device line (one tab)
            if line.startswith('\t'):
                if current_vendor is None:
                    continue
                rest = line[1:]  # strip leading tab
                m = re.match(r'^([0-9a-fA-F]{4})\s{2}(.+)$', rest)
                if m:
                    pid  = int(m.group(1), 16)
                    name = m.group(2).strip()
                    if name:
                        current_vendor[2].append((pid, name))
                continue

            # Vendor line (no leading whitespace)
            m = re.match(r'^([0-9a-fA-F]{4})\s{2}(.+)$', line)
            if m:
                vid  = int(m.group(1), 16)
                name = m.group(2).strip()
                if name:
                    current_vendor = (vid, name, [])
                    vendors.append(current_vendor)
            # anything else (e.g. "C <class>") — ignore

    return vendors

def main():
    if len(sys.argv) < 2:
        print("Usage: gen_usb_ids.py <usb.ids> [output.h]", file=sys.stderr)
        sys.exit(1)

    input_path  = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else None

    vendors = parse_usb_ids(input_path)

    # Build flat sorted entry list: (vid, pid, vendor_str, product_str)
    # pid == 0xFFFF marks a vendor-only entry (no specific product known)
    entries = []
    for (vid, vname, devices) in vendors:
        entries.append((vid, 0xFFFF, vname, "USB Device"))
        for (pid, pname) in devices:
            entries.append((vid, pid, vname, pname))

    # Sort by (vid, pid) — 0xFFFF vendor entries sort after all real PIDs
    # but we want them FIRST within each VID group for fallback logic.
    # So sort vendor-only (pid=0xFFFF) before real PIDs by using pid=-1 key.
    entries.sort(key=lambda e: (e[0], -1 if e[1] == 0xFFFF else e[1]))

    total    = len(entries)
    n_vendor = sum(1 for e in entries if e[1] == 0xFFFF)
    n_device = total - n_vendor

    lines = []
    lines.append("/*")
    lines.append(" * usb_ids_generated.h")
    lines.append(" * Auto-generated by gen_usb_ids.py — DO NOT EDIT")
    lines.append(f" * Source: {input_path}")
    lines.append(f" * Entries: {n_vendor} vendors, {n_device} devices, {total} total")
    lines.append(" *")
    lines.append(" * Lookup: usb_id_find(vid, pid, &vendor, &product)")
    lines.append(" *   Returns 1 exact match, 0 vendor-only, -1 unknown.")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef USB_IDS_GENERATED_H")
    lines.append("#define USB_IDS_GENERATED_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    uint16_t    vid;")
    lines.append("    uint16_t    pid;      /* 0xFFFF = vendor-only entry */")
    lines.append("    const char *vendor;")
    lines.append("    const char *product;")
    lines.append("} usb_id_entry_t;")
    lines.append("")
    lines.append(f"#define USB_ID_TABLE_SIZE {total}U")
    lines.append("")
    lines.append("static const usb_id_entry_t usb_id_table[USB_ID_TABLE_SIZE] = {")

    for (vid, pid, vendor, product) in entries:
        pid_str = "0xFFFF" if pid == 0xFFFF else f"0x{pid:04X}"
        lines.append(
            f'    {{ 0x{vid:04X}, {pid_str}, '
            f'"{escape_c(vendor)}", '
            f'"{escape_c(product)}" }},'
        )

    lines.append("};")
    lines.append("")
    lines.append("/*")
    lines.append(" * usb_id_find — binary search in usb_id_table.")
    lines.append(" *")
    lines.append(" * Searches first for an exact (vid, pid) match.")
    lines.append(" * If not found, falls back to the vendor-only entry (pid == 0xFFFF).")
    lines.append(" * Fills *vendor_out and *product_out with static string pointers.")
    lines.append(" * Returns: 1 exact, 0 vendor-only, -1 not found.")
    lines.append(" */")
    lines.append("static inline int usb_id_find(uint16_t vid, uint16_t pid,")
    lines.append("                               const char **vendor_out,")
    lines.append("                               const char **product_out) {")
    lines.append("    /* Binary search for exact (vid, pid) match.")
    lines.append("     * Table is sorted by (vid asc, pid asc) with 0xFFFF first per vendor. */")
    lines.append("    int lo = 0, hi = (int)USB_ID_TABLE_SIZE - 1;")
    lines.append("    const char *vendor_fallback = (void*)0;")
    lines.append("    const char *product_fallback = (void*)0;")
    lines.append("")
    lines.append("    while (lo <= hi) {")
    lines.append("        int mid = lo + (hi - lo) / 2;")
    lines.append("        const usb_id_entry_t *e = &usb_id_table[mid];")
    lines.append("")
    lines.append("        if (e->vid < vid || (e->vid == vid && e->pid < pid)) {")
    lines.append("            /* Check if this is the vendor-only fallback for our VID */")
    lines.append("            if (e->vid == vid && e->pid == 0xFFFF) {")
    lines.append("                vendor_fallback  = e->vendor;")
    lines.append("                product_fallback = e->product;")
    lines.append("            }")
    lines.append("            lo = mid + 1;")
    lines.append("        } else if (e->vid > vid || (e->vid == vid && e->pid > pid)) {")
    lines.append("            /* While scanning downward, also capture vendor-only */")
    lines.append("            if (e->vid == vid && e->pid == 0xFFFF) {")
    lines.append("                vendor_fallback  = e->vendor;")
    lines.append("                product_fallback = e->product;")
    lines.append("            }")
    lines.append("            hi = mid - 1;")
    lines.append("        } else {")
    lines.append("            /* Exact match */")
    lines.append("            *vendor_out  = e->vendor;")
    lines.append("            *product_out = e->product;")
    lines.append("            return 1;")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    /* No exact match — try vendor-only fallback */" )
    lines.append("    if (vendor_fallback) {")
    lines.append("        /* Linear scan to find the 0xFFFF entry for this VID")
    lines.append("         * (binary search may have missed it during the walk) */")
    lines.append("        *vendor_out  = vendor_fallback;")
    lines.append("        *product_out = product_fallback;")
    lines.append("        return 0;")
    lines.append("    }")
    lines.append("")
    lines.append("    /* Fallback: scan linearly for vendor-only entry */")
    lines.append("    for (int i = 0; i < (int)USB_ID_TABLE_SIZE; i++) {")
    lines.append("        if (usb_id_table[i].vid == vid &&")
    lines.append("            usb_id_table[i].pid == 0xFFFF) {")
    lines.append("            *vendor_out  = usb_id_table[i].vendor;")
    lines.append("            *product_out = usb_id_table[i].product;")
    lines.append("            return 0;")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append('    *vendor_out  = "Unknown";')
    lines.append('    *product_out = "USB Device";')
    lines.append("    return -1;")
    lines.append("}")
    lines.append("")
    lines.append("#endif /* USB_IDS_GENERATED_H */")

    output = '\n'.join(lines) + '\n'

    if output_path:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(output)
        print(f"Written {total} entries ({n_vendor} vendors, {n_device} devices) to {output_path}",
              file=sys.stderr)
    else:
        sys.stdout.write(output)
        print(f"Written {total} entries ({n_vendor} vendors, {n_device} devices) to stdout",
              file=sys.stderr)

if __name__ == '__main__':
    main()